# Configure dependencies for CONFIG_MCUMGR_GRP_IMG  
CONFIG_FLASH=y
CONFIG_IMG_MANAGER=y

# Configure dependencies for CONFIG_IMG_MANAGER  
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y

# Configure dependencies for CONFIG_MCUMGR_TRANSPORT_UART 
CONFIG_BASE64=y

#enable floats
CONFIG_FPU=y
CONFIG_CBPRINTF_FP_SUPPORT=y

#IMU sensor
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_LIS2DS12=y

#RCT config
CONFIG_RTC=y
CONFIG_RTC_RV3028=y

#GPIO config
CONFIG_GPIO=y
#FLASH setup

CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_SPI_NOR_SFDP_RUNTIME=y 

CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_JESD216_API=y
#CONFIG_SPI_NOR_FLASH_LAYOUT_PAGE_SIZE=4096
# --- NEW: LittleFS Support ---
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y
# LittleFS needs sufficient heap for its operations and formatting
#CONFIG_HEAP_MEM_POOL_SIZE=32768
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=n
CONFIG_PM_PARTITION_REGION_LITTLEFS_EXTERNAL=y
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y
#Do not chagne, THIS IS ON PURPOSE 0
CONFIG_PM_PARTITION_SIZE_LITTLEFS=0x0

# CONFIG_FILE_SYSTEM_INIT_PRIORITY=41
# Optional: Enable FS logging to see mount/format activity
CONFIG_FS_LOG_LEVEL_DBG=n

CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=n   # keep off unless you specifically need it
CONFIG_POWEROFF=y

# USB CDC ACM (Virtual COM Port)
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_VID=0x2FE3
CONFIG_USB_DEVICE_PID=0x0001
CONFIG_USB_DEVICE_MANUFACTURER="MyCompany"
CONFIG_USB_DEVICE_PRODUCT="nRF52833 Data Transfer"
CONFIG_CRC=y
#autostart usb so printk works
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_BOOT_BANNER=n

CONFIG_THREAD_MONITOR=y

# VBUS API for USB dedtection
CONFIG_NRFX_POWER=y

# Serial / UART for CDC
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y

# Shell functionality
# --- Shell ---
CONFIG_SHELL=y
CONFIG_SHELL_THREAD_PRIORITY=14
CONFIG_SHELL_BACKEND_SERIAL=y      # CDC-ACM UART counts as "serial" backend
CONFIG_SHELL_STACK_SIZE=4096
CONFIG_SHELL_CMD_BUFF_SIZE=128
CONFIG_SHELL_ARGC_MAX=12
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_HISTORY_BUFFER=512
CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
CONFIG_SHELL_ECHO_STATUS=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_UART_CONSOLE=y

# Ring buffer for lossless buffering
CONFIG_RING_BUFFER=y
#CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y

# Logging (optional, redirect to RTT to avoid USB conflicts)
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=256
CONFIG_SHELL_BACKEND_SERIAL_TX_RING_BUFFER_SIZE=8192

# System
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_SHELL_STACK_SIZE=6144